language: node_js
services:
  - xvfb
sudo: false
jobs:
  include:
    - node_js: 8
      env: EXTRA=false
    - node_js: 10
      env: EXTRA=true
    - node_js: 14
      env: EXTRA=false
before_install:
  - npm install -g karma-cli
before_script:
  - npm install karma-sauce-launcher
script:
  - npm test
  - "[ $EXTRA = false ] || npm run test-browser"
  - "[ $EXTRA = false ] || karma start karma.conf-sauce.js"
  - "[ $EXTRA = false ] || npm run coveralls"
notifications:
  email: false
env:
  global:
  - NPM_CONFIG_PROGRESS="false"
  - secure: bDZSBQfqr21hCayjcZ20IxrV6+XGhxQPFIfwWqEKLrF93Gu8LLVjZRxXE/mE8I8N4Z5WtDNb4ZHrm/TTzmcPa5MuHgIxEdknQCncobH8oimwc83SHwEPk6okeNKl39VlCjvvnmoe/V/KpnknuYn3Rqghtl/Uv9KLpCwskwjTtcw=
  - secure: SRECgXuwcZTcD3GVxTS2bYNgRyye4vq6BLrV2PH9FyNenowsKQR2EwlC/dppc1Q8NWMgv79J/R96q9JOFh+mEH9L5dlBb2yhnGH8amVeM/ChAJHT/F8YktKM453uVpz5fR00QcCQDDUOx6Pvx374ID0OKNpWKAkQBWA9mPTsLnE=
